### PR TITLE
chore(*): update SDK to v2.6.0

### PR DESCRIPTION
**Pull request by drew-thompson**
@Only1MrAnderson It'd be great to update the library to use the newest SDK version, which purportedly fixes a number of bugs and adds native screen-sharing capabilities to Chrome.

https://docs.agora.io/en/Video/release_web_video?platform=Web#v2-6-0

### CODE REVIEW

**Comment by Only1MrAnderson** [comment]
@drew-thompson I agree, sadly I no longer am working on this package. 
@digitallysavvy I see you have been merging PRs lately, can you have someone reach out to me so I can transfer the NPM package.  I still 'own' it and it has not been updated in 8 months....

**Comment by drew-thompson** [comment]
@Only1MrAnderson, this PR aside, did you need to do anything specific to package the SDK into your library? I've tried to reproduce the library setup and was able to build the library, but trying to use it locally gives me the error `Can't resolve 'agora-rtc-sdk' in '...fesm5'`.

You're obviously not obligated to assist with this, but I would definitely appreciate any tips you have - thanks!

**Comment by Only1MrAnderson** [comment]
@drew-thompson The SDK is packaged using npm and dev dependencies. see `projects/angular-agora-rtc/package.json`
```
  "dependencies": {
    "agora-rtc-sdk": "^2.3.1"
  }
```

I was unable to get your PR to run with 2.6.0 as well. The recommended way would be to cd into the project and install the latest version of `agora-rtc-sdk`. Which at this point is 2.5.2

I think a PR is needed for `agora-rtc-sdk` to get them to bump the version, then update this PR.

**Comment by drew-thompson** [comment]
> @drew-thompson The SDK is packaged using npm and dev dependencies. see `projects/angular-agora-rtc/package.json`
> 
> ```
>   "dependencies": {
>     "agora-rtc-sdk": "^2.3.1"
>   }
> ```
> I was unable to get your PR to run with 2.6.0 as well. The recommended way would be to cd into the project and install the latest version of `agora-rtc-sdk`. Which at this point is 2.5.2
> 
> I think a PR is needed for `agora-rtc-sdk` to get them to bump the version, then update this PR.

@Only1MrAnderson Absolutely, that'd be the best way to do it, just following suite with the last update PR because _Agora_ hasn't updated their package to `2.6.0` yet.

Thanks for the guidance on my question, I saw the included dependency, but my local version wasn't packaging the library into the build. Using a different approach now though, but thanks all the same!

**Comment by digitallysavvy** [comment]
@Only1MrAnderson @drew-thompson The official Agora NPM package has been updated to `v2.6.1` ... apologies for the delay. The engineering team was working on the hot fix _(`v2.6.1`)_ so `v2.6.0` was skipped for this reason.

**Comment by drew-thompson** [comment]
@digitallysavvy Thank you!

**Pull request closed without merging**
